config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :admins

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'customers#new'

  resources :customers

  resources :admins

  resources :super_admins

  resources :records


  resources :cars do
    member do
      get 'schedule'
      post 'action'
      patch 'action'
      get 'beforecheckout'
      get 'subscribe'
     # get 'checkout'
      get 'return'
      post 'reserve'
      get 'cancel'
      get 'approve'
      get 'disapprove'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/super_admins_controller.rb
class SuperAdminsController < ApplicationController
  before_action :set_super_admin, only: %i[show edit update destroy]
  before_action :back_if_not_logged_in
  before_action :back_if_customer
  before_action :back_if_admin
  before_action :back_if_not_self_supoer_admin, only: %i[edit]

  # GET /super_admins
  # GET /super_admins.json
  def index
    @super_admins = SuperAdmin.all
  end

  # GET /super_admins/1
  # GET /super_admins/1.json
  def show
  end

  # GET /super_admins/new
  def new
    @super_admin = SuperAdmin.new
  end

  # GET /super_admins/1/edit
  def edit
  end

  # POST /super_admins
  # POST /super_admins.json
  def create
    unless Customer.find_by(email: params[:super_admin][:email]).nil? && Admin.find_by(email: params[:super_admin][:email]).nil?
      redirect_to new_super_admin_url
      return
    end
    @super_admin = SuperAdmin.new(super_admin_params)

    respond_to do |format|
      if @super_admin.save
        format.html { redirect_to @super_admin, notice: 'Super admin was successfully created.' }
        format.json { render :show, status: :created, location: @super_admin }
      else
        format.html { render :new }
        format.json { render json: @super_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /super_admins/1
  # PATCH/PUT /super_admins/1.json
  def update
    respond_to do |format|
      params[:super_admin][:email].downcase!
      params[:super_admin][:name].downcase!
      if @super_admin.update(super_admin_params)
        format.html { redirect_to @super_admin, notice: 'Super admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @super_admin }
      else
        format.html { render :edit }
        format.json { render json: @super_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /super_admins/1
  # DELETE /super_admins/1.json
  def destroy
    @super_admin.destroy
    respond_to do |format|
      format.html { redirect_to super_admins_url, notice: 'Super admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_super_admin
      @super_admin = SuperAdmin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def super_admin_params
      params.require(:super_admin).permit(:name, :email, :password, :password_comfirmation)
    end
end

app/helpers/super_admins_helper.rb
module SuperAdminsHelper
end

app/views/super_admins/_form.html.erb
<%= form_with(model: super_admin, local: true) do |form| %>
  <% if super_admin.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(super_admin.errors.count, "error") %> prohibited this super_admin from being saved:</h2>

      <ul>
      <% super_admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :super_admin_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :super_admin_email %>
  </div>

    <%= form.label :password %>
    <%= form.password_field :password %>

    <%= form.label :password_confirmation, 'Confirmation' %>
    <%= form.password_field :password_confirmation %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/super_admins/edit.html.erb
<h1>Editing Super Admin</h1>

<%= render 'form', super_admin: @super_admin %>

<%= link_to 'Show', @super_admin %> |
<%= link_to 'Back', super_admins_path %>

app/views/super_admins/index.html.erb
<p id="notice"><%= notice %></p>
<h2>SuperAdmins </h2>
<table style="margin:0 auto">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @super_admins.each do |super_admin| %>
      <tr>
        <td><%= super_admin.name %></td>
        <td><%= super_admin.email %></td>
        <td><%= link_to 'Show', super_admin %></td>
        <% if current_user == @super_admin %>
           <td><%= link_to 'Edit', edit_super_admin_path(super_admin) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

</table>
<br><br><br>
<%= link_to 'New SuperAdmin', new_super_admin_path %>

<br>

app/views/super_admins/new.html.erb
<h1>New Super Admin</h1>

<%= render 'form', super_admin: @super_admin %>

<%= link_to 'Back', super_admins_path %>

app/views/super_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @super_admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @super_admin.email %>
</p>
<% if current_user == @super_admin %>
    <%= link_to 'Edit', edit_super_admin_path(@super_admin) %> |
<% end %>
<%= link_to 'Back', super_admins_path %>