config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :admins

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'customers#new'

  resources :customers

  resources :admins

  resources :super_admins

  resources :records


  resources :cars do
    member do
      get 'schedule'
      post 'action'
      patch 'action'
      get 'beforecheckout'
      get 'subscribe'
     # get 'checkout'
      get 'return'
      post 'reserve'
      get 'cancel'
      get 'approve'
      get 'disapprove'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<% provide(:title, 'Create an Admin') %>

<h1>Create</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin) do |f| %>
        <% if @admin.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                The form contains <%= pluralize(@admin.errors.count, "error") %>.
              </div>
              <ul style="text-align: center">
                <% @admin.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>
        <div class="field">
        </div>
        <div class="field">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', @admin %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Admins</h2>

<table style="margin:0 auto">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Show', admin %></td>
        <% if current_user == admin %>
            <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <% end %>
        <% if (current_authority == $admin && current_user.id != admin.id) || current_authority == $superadmin %>
            <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

</table>
<br><br><br>
<%= link_to 'New Admins', new_admin_path %>

<br>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>
<% if (current_authority == $admin && current_user == @admin) || current_authority == $superadmin %>
    <%= link_to 'Edit', edit_admin_path(@admin) %> |
<% end %>
<%= link_to 'Back', admins_path %>
<br><br>
<%= link_to 'Create New Admin', new_admin_path %>