config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :admins

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'customers#new'

  resources :customers

  resources :admins

  resources :super_admins

  resources :records


  resources :cars do
    member do
      get 'schedule'
      post 'action'
      patch 'action'
      get 'beforecheckout'
      get 'subscribe'
     # get 'checkout'
      get 'return'
      post 'reserve'
      get 'cancel'
      get 'approve'
      get 'disapprove'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  before_save {
    self.manufacturer = manufacturer.downcase
    self.model = model.downcase
    self.location = location.downcase
  }
  has_many :records, dependent: :destroy
  validates :license,
            presence: true,
            length: { is: 7},
            uniqueness: true
  validates :manufacturer, presence: true
  validates :model, presence: true
  validates :rate, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :style,
            presence: true,
            inclusion: {
              in: %w[Sedan SUV Coupe],
              message: '%<value>s is not a valid style'
            }
  validates :location, presence: true
  validates :status,
            presence: true,
            inclusion: {
              in: ['Available', 'Reserved', 'Checked Out', 'Suggested'],
              message: '%<value>s is not a valid status'
            }

  def update_status(status)
    update_attribute(:status, status)
  end
  
  def update_customer_id(id)
    update_attribute(:customer_id, id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  require "date"
  before_action :set_car,
                except: %i[index new create checkout]
  before_action :set_customer,
                only: %i[action schedule reserve beforecheckout return cancel subscribe]
  before_action :back_if_not_logged_in
  before_action :back_if_customer, only: %i[approve disapprove]
  before_action :back_if_not_suggestion_owner,
                only: %i[edit update destroy]
  before_action :back_if_admin_edit_suggestion,
                only: :edit
  after_action  :delete_customer_pin,
                only: %i[reserve checkout return cancel]

  # GET /cars
  # GET /cars.json
  def index
    @cars = if current_authority == $customer
                 Car.where('status != ? or customer_id = ?', $suggested, current_user.id)# display suggested car by customer self
               else
                 Car.all
               end

    attribute = params[:attribute]
    value = params[:value]
    @cars = @cars.where("#{attribute.downcase} = ?", value.downcase) unless value.nil? || value.blank?

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
      if @car.status == $reserved
        @records = Record.where('status = ? and car_id =?', $reserved, @car.id).order( :start )
      end
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def approve
    customer = Customer.find_by(id: @car.customer_id)
    customer.update_car_id(nil)
    @car.update(status: $available, customer_id: nil)
    CustomerMailer.approve_email(customer, @car).deliver_now
    redirect_to @car,
                notice: 'Suggestion has been approved.'
  end

  def disapprove
    Customer.find_by(id: @car.customer_id).update_car_id(nil)
    @car.destroy
    redirect_to cars_url,
                notice: 'Suggestion has been disapproved.'
  end

  def action
    pin_customer(@customer)
    if params[:reserve_btn]
      redirect_to schedule_car_path(id: @car.id)
    elsif params[:checkout_btn]
      redirect_to beforecheckout_car_url(id: @car.id, h: params[:h])
    elsif params[:return_btn]
      redirect_to return_car_url(id: @car.id)
    elsif params[:subscribe_btn]
      redirect_to subscribe_car_url(id: @car.id)
    else
      redirect_to cancel_car_url(id: @car.id)
    end
  end

  def subscribe
    @customer.update_subscribe_car_id(@car.id)
    respond_to do |format|
      format.html { redirect_to @car, notice: 'Car was successfully subscribed, you will receive a email when car is available'; return }
      format.json { head :no_content }
    end

  end

  def schedule
    subject = if current_authority == $customer
                'you have '
              else
                'this customer has '
              end
    if @customer.status != $returned
      respond_to do |format|
        format.html { redirect_to @car, notice: 'Failed, ' + subject + 'already reserved or checked out another car.'; return }
        format.json { head :no_content }
      end
    end
  end

  def findNext car, customer
    reservations = Record.where('status = ? and car_id =? and customer_id != ?',
                                $reserved, car.id, customer.id).order( :start )
    if reservations.size == 0
      car.update_status($available)
      car.update_attribute(:customer_id, "")
      subscribes = Customer.where('subscribe_car_id =? ', car.id)
      subscribes.each do |one|
        one.update_attribute(:subscribe_car_id, "")
        CustomerMailer.available_email(one, car).deliver_now
      end
    else
      nextone = reservations.first # next reservation
      car.update_status($reserved)
      car.update_attribute(:customer_id, "#{nextone.customer_id}")

    end
  end

  def reserve
    start_time = Time.new(params[:start_date][:year].to_i,
                          params[:start_date][:month].to_i,
                          params[:start_date][:day].to_i,
                          params[:start_date][:hour].to_i,
                          params[:start_date][:minute].to_i,
                          0)# has to add 59s to ensure start time is valid
    hours= params[:h].to_i
    end_time = start_time +  hours.hour
    #end_time = Time.new(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i, params[:end_date][:hour].to_i, params[:end_date][:minute].to_i, 0, "-04:00")
    if start_time + 59.second < Time.zone.now || start_time > Time.zone.now + 7.days
      respond_to do |format|
        format.html { redirect_to @car, notice: 'Start Time is not valid.'; return }
        format.json { head :no_content }
      end
    end

    if @car.status == $reserved
      @records = Record.where('status = ? and car_id =?', $reserved, @car)
      @records.each do |record|
        unless end_time < record.start || start_time > record.end  # check whether reservation time is overlaped
          respond_to do |format|
            format.html { redirect_to @car, notice: 'The car has been reserved during this time period.'; return }
            format.json { head :no_content }
          end
        end
      end
      #  reservation is valid
      if start_time < @records.minimum(:start)
        @car.update_attribute(:customer_id, "#{@customer.id}")
      end
    else
      @car.update_status($reserved)
      @car.update_attribute(:customer_id, "#{@customer.id}")
    end
    record = Record.create(customer_id: @customer.id,
                           car_id: @car.id,
                           start: start_time,
                           end: end_time,
                           hours: hours,
                           status: $reserved)
    @customer.update_status($reserved)
    @customer.update_car_id(@car.id)
    @customer.update_record_id(record.id)
    ########################################
    #  Timer

      elasticity = record.start + 30.minute
          #elasticity = record.start + 20.second
      job_id = $scheduler.at elasticity.to_s do
        record = Record.find_by(id: @customer.record_id)
        record.update_status($cancelled)
        record.update_hours("0")
        @customer.update_status($returned)
        @customer.update_record_id(nil)
          @customer.update_car_id(nil)
        @customer.update_attribute(:job_id, "")

        findNext @car, @customer
      end
      @customer.update_attribute(:job_id, "#{job_id}")
    ########################################
    respond_to do |format|
      format.html { redirect_to @car, notice: 'Car was successfully reserved.'; return }
      format.json { head :no_content }
    end

  end

  def beforecheckout
    subject = if current_authority == $customer
                'you have '
              else
                'this customer has '
              end
    if @customer.status == $checkedout
      respond_to do |format|
        format.html { redirect_to @car, notice: 'Failed, ' + subject  + 'checked out another car!'; return }
        format.json { head :no_content }
      end
    elsif @customer.status == $reserved
      if @customer.car_id == @car.id
        if @car.customer_id != @customer.id  # check this car belongs to whom
          respond_to do |format|
            format.html { redirect_to @car, notice: 'Failed, ' + subject  + 'reserved in another time '; return }
            format.json { head :no_content }
          end
          else
            record = Record.find_by(id: @customer.record_id)
            if record.start > Time.zone.now
              respond_to do |format|
                format.html { redirect_to @car, notice: 'Failed, ' + subject  + 'to wait until your appointment time '; return }
                format.json { head :no_content }
              end
            else
              unless $scheduler.job(@customer.job_id).nil?
                $scheduler.job(@customer.job_id).unschedule
              end
              record.update_status($checkedout)
              checkout(@car,@customer,record)
            end
        end
      else
        respond_to do |format|
          format.html { redirect_to @car, notice: 'Failed, ' + subject  + 'reserved another car '; return }
          format.json { head :no_content }
        end
      end
    elsif @car.status == $reserved
            respond_to do |format|
              format.html { redirect_to @car, notice: 'Failed, ' + subject + 'not reserved this car'; return }
              format.json { head :no_content }
            end
    else
      record = Record.create(customer_id: @customer.id,
                             car_id: @car.id,
                             start: Time.zone.now,
                             hours: params[:h].to_i,
                             status: $checkedout)

      endtime = record.start + record.hours.hour
      record.update_end(endtime)
      @car.update_attribute(:customer_id, "#{@customer.id}")
      @customer.update_record_id(record.id)
      @customer.update_car_id(@car.id)
      checkout(@car,@customer,record)
    end
  end

  def checkout car, customer, record
    customer.update_status($checkedout)
    car.update_status($checkedout)
########################################
#  Open Timer （call return method）  endtime  change to available
        #tmp = record.start +  40.second  #  should comment
       # job_id= $scheduler.at tmp.to_s do
      job_id= $scheduler.at record.end do
          record.update_status($returned)
          CustomerMailer.return_email(customer, car).deliver_now
          charge = customer.charge + car.rate * record.hours

          customer.update_status($returned)
          customer.update_attribute(:car_id, "")
          customer.update_attribute(:record_id,"")
          customer.update_charge(charge)
          customer.update_attribute(:job_id, "")

          findNext car, customer
      end
      customer.update_attribute(:job_id, "#{job_id}")
########################################
    respond_to do |format|
      format.html { redirect_to car, notice: 'Car was successfully checked out.'; return }

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
    <% if car.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% car.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license, id: :car_license %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, id: :car_manufacturer %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate, id: :car_rate %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.select :style, [ 'Sedan', 'Coupe', 'SUV'], :prompt => 'Select One' %>

  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :car_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<% if current_authority != $customer %>
    <h1>Editing Car</h1>
<% else %>
    <h1>Editing Suggestion</h1>
<% end %>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cars</h2>

<%= form_tag(cars_path, method: 'get') do %>
    <%= label_tag(:value, 'Search by:') %>
    <%= select_tag :attribute, options_for_select(%w[Location Model Manufacturer Style Status]) %>
    <%= text_field_tag(:value) %>
    <%= submit_tag('Search') %>
<% end %>

<br>
<br>

<table style="margin:0 auto">
  <thead>
    <tr>
      <th>License</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Rate</th>
      <th>Style</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.license %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.model %></td>
        <td><%= car.rate %></td>
        <td><%= car.style %></td>
        <td><%= car.location %></td>
        <td><%= car.status %></td>
        <td><%= link_to 'Check Details to rent', car %></td>
        <% if car.status == $suggested %>
            <% if current_authority == $customer %>
                <td><%= link_to 'Edit Suggestion', edit_car_path(car) %></td>
                <td><%= link_to 'Retrieve Suggestion', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
                <td><%= link_to 'Approve Suggestion', approve_car_path(car) %></td>
                <td><%= link_to 'Disapprove Suggestion', disapprove_car_path(car) %></td>
            <% end %>
        <% else %>
            <% if current_authority != $customer %>
                <td><%= link_to 'Edit', edit_car_path(car) %></td>
                <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>



<br>
<% if current_authority != $customer %>
    <%= link_to 'New Car', new_car_path %>
<% else %>
    <%= link_to 'Suggest a New Car', new_car_path %>
<% end %>

app/views/cars/new.html.erb
<% if current_authority != $customer %>
    <h1>New Car</h1>
<% else %>
    <h1>New Suggestion</h1>
<% end %>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/schedule.html.erb
<%= form_tag(reserve_car_path(@car)) do %>
    <strong>Check Out Time:</strong>
    <%= select_datetime  Time.now, prefix: :start_date %>
    <%= "(*Within 7 days)" %>
    <br>
    <br>
    <strong>Rental Hours:     </strong>
    <%= select_tag :h, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
    <%= submit_tag('Reserve') %>
<% end %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License:</strong>
  <%= @car.license %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @car.rate %>
</p>

<p>
  <strong>Style:</strong>
  <%= @car.style %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<p>
  <% unless @car.customer_id.nil? || (current_authority == $customer && current_user.id != @car.customer_id) %>
  <strong>Relative to:</strong>
      <%= Customer.find_by(id: @car.customer_id).email %>
  <% end %>
</p>

<% if @car.status == $reserved && @records.size != 0 %>

    <table style="margin-left:300px">

      <strong>Reserve History:</strong>
      <thead>
      <tr>
        <th>Car License</th>
        <th>Customer</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Duration</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @records.each do |record| %>
          <tr>
            <td><%= record.car.license %></td>
            <td><%= record.customer.email %></td>
            <td><%= record.start.in_time_zone('Eastern Time (US & Canada)')%></td>
            <td><%= record.end.in_time_zone('Eastern Time (US & Canada)') %></td>
            <td><%= record.hours %></td>
            <td><%= record.status %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>
<% end %>





<% if current_authority != $customer && @car.status != $suggested %>
    <%= link_to 'Edit', edit_car_path(@car) %> |
    <%= link_to 'Destroy', @car, method: :delete, data: { confirm: 'Are you sure?' } %>
<% elsif current_authority != $customer && @car.status == $suggested %>
    <%= link_to 'Approve Suggestion', approve_car_path(@car) %> |
    <%= link_to 'Disapprove Suggestion', disapprove_car_path(@car) %>
<% elsif current_authority == $customer && @car.status == $suggested %>
    <%= link_to 'Edit Suggestion', edit_car_path(@car) %> |
    <%= link_to 'Retrieve Suggestion', @car, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<% if @car.status == $available %>
    <% if current_authority != $customer %>
      <%= form_for @car, url: {action: 'action'} do |f| %>
            <%= f.label :customer_id, 'Customer' %>
            <%= collection_select :customer, :customer_id, Customer.all, :id, :email %>
            <br>
            <br>
                <%= submit_tag 'Reserve', name: 'reserve_btn' %>
            <br>
                <p>
                  <strong>Rant Time:</strong>
                  <%= select_tag :h, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
                  <%= submit_tag 'Check Out', name: 'checkout_btn' %>
                </p>
      <% end %>
     <% elsif current_user.status == $returned %>
        <%= form_for @car, url: {action: 'action'} do |f| %>
            <br>
            <%= submit_tag 'Reserve', name: 'reserve_btn' %>
            <p>
              <strong>Rent Time:</strong>
              <%= select_tag :h, options_for_select([['1', 1], ['2', 2], ['3', 3],['4', 4],['5', 5],['6', 6],['7', 7],['8', 8],['9', 9],['10',10]]) %>
              <%= submit_tag 'Check Out', name: 'checkout_btn' %>
            </p>
        <% end %>
     <% end %>
<% elsif @car.status == $reserved %>
    <% if current_authority != $customer %>
        <%= form_for @car, url: {action: 'action'} do |f| %>
            <%= f.label :customer_id, 'Customer' %>
            <%= collection_select :customer, :customer_id, Customer.all, :id, :email %>
            <br>
            <br>
            <%= submit_tag 'Reserve', name: 'reserve_btn' %>
            <p>
              <%= submit_tag 'Check Out', name: 'checkout_btn' %>
            </p>
            <%= submit_tag 'Cancel Reservation', name: 'cancel_btn' %>
        <% end %>

    <% else %> <!-- customer -->
        <%= form_for @car, url: {action: 'action'} do |f| %>
            <% if @car.customer_id == current_user.id %>
                <%= submit_tag 'Check Out', name: 'checkout_btn' %>
                <br>
                <br>
                <%= submit_tag 'Cancel Reservation', name: 'cancel_btn' %>
            <% elsif current_user.status == $returned %>
                <%= submit_tag 'Reserve', name: 'reserve_btn' %>
            <% end%>
        <% end %>
    <% end %>
<% elsif @car.status == $checkedout%>
    <% if current_authority != $customer %>
        <%= form_for @car, url: {action: 'action'} do |f| %>
            <%= f.label :customer_id, 'Customer' %>
            <%= collection_select :customer, :customer_id, Customer.all, :id, :email %>
            <br>
            <br>
            <%= submit_tag 'Return', name: 'return_btn' %>
        <% end %>
    <% else %>
         <%= form_for @car, url: {action: 'action'} do |f| %>
            <% if @car.customer_id == current_user.id %>
                <%= submit_tag 'Return', name: 'return_btn' %>
            <% elsif current_user.subscribe_car_id == nil%>
                <%= submit_tag 'Subscribe a email notification', name: 'subscribe_btn' %>
            <% end %>
        <% end %>
     <% end %>
<% end %>
<br><br>