config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :admins

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'customers#new'

  resources :customers

  resources :admins

  resources :super_admins

  resources :records


  resources :cars do
    member do
      get 'schedule'
      post 'action'
      patch 'action'
      get 'beforecheckout'
      get 'subscribe'
     # get 'checkout'
      get 'return'
      post 'reserve'
      get 'cancel'
      get 'approve'
      get 'disapprove'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
      body {background-color: burlywood}
    </style>
  </head>
<style>

</style>
  <body style="font-size:20px;text-align: center">
    <% if logged_in? %>
      <h1 style="color:saddlebrown;text-align: center"> Welcome, <%= current_user.name %></h1>
      <br>
      <% if current_authority != $customer %>
          <%= link_to 'Records', records_path %>|
          <%= link_to 'Customers', customers_path %> |
          <%= link_to 'Admins', admins_path %> |
      <% end %>
      <% if current_authority == $superadmin %>
          <%= link_to 'Super Admins', super_admins_path %>|
      <% end %>
      <% if current_authority == $customer %>
          <%= link_to 'My Record', records_path %>|
      <% end %>
      <%= link_to 'Cars', cars_path %>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'My Profile', current_user %>|
      <%= link_to 'Log Out', logout_path, method: :delete %>
  <% end %>
  <br>
  <br>
    <%= yield %>


  </body>

</html>